# Generated by Django 4.0.1 on 2022-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
                ('first_client', models.CharField(max_length=30, null=True)),
                ('second_client', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
